---
title: "Exercise_05_Challenge_1"
author: "SLCornett"
date: "2/21/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(mosaic)
library(dplyr)
library(ggplot2)
```
Functions in the {mosaic} package have a *data=* argument as well as a *~* argument that specifies which variable of interest from the data= argument the function is to be applied to.

```{r}
f <- "https://raw.githubusercontent.com/difiore/ada-2022-datasets/main/IMDB-movies.csv"
d <- read_csv(f, col_names = TRUE)
df<- d %>% filter(startYear %in% 1920:1979, runtimeMinutes %in% 60:180) %>%
  mutate("decade"=case_when(startYear %in% 1920:1929~"20s",
                            startYear %in% 1930:1939~"30s",
                            startYear %in% 1940:1949~"40s",
                            startYear %in% 1950:1959~"50s",
                            startYear %in% 1960:1969~"60s",
                            startYear %in% 1970:1979~"70s"
                            )
         )
print(df)
```
Table has 5,651 items

Use {ggplot2} (which is part of {tidyverse}) to plot histograms of the distribution of runtimeMinutes for each decade
```{r}
# boxplot(runtimeMinutes ~ startYear, data=df, xlab="Decade", ylab="runtime (min)") #test that decade works in general, it does
p <- ggplot(data = df)  #object built (in theory) -> don't need aes(x, y) here because R gets confused and angry
p <- p + xlab("Runtime (min)") + ylab("Density") #data labels
#p <- p + geom_point(na.rm=TRUE) # makes a "scatterplot" that's more a bar graph of dots

#p <- p + histogram(~ decades, data = df$runtimeMinutes, xlab = "Runtime (min)") #incompatable and also just doesn't work with ggplot2, or on its own
p<- p + geom_histogram(aes(x=runtimeMinutes,#no need y= or stat=identity
                                    color=factor(decade),
                                    binwidth = 30,
                                    na.rm=TRUE
                                    )) #x, y, alpha, color, fill, linetype, size, weight
p

p <- p + facet_wrap(~ decade, ncol=4) # wrap data "by" decade into 4 columns
p
```

